export const UPDATE_RESTROOMS = "UPDATE_RESTROOMS";

export const ADD_TO_DONATIONCART = "ADD_TO_DONATIONCART";
export const ADD_MULTIPLE_TO_DONATIONCART = "ADD_MULTIPLE_TO_DONATIONCART";
export const REMOVE_FROM_DONATIONCART = "REMOVE_FROM_DONATIONCART";
export const CLEAR_DONATIONCART = "CLEAR_DONATIONCART";
export const UPDATE_USDAMT = "UPDATE_DONATIONCART_QUANTITY";
export const TOGGLE_DONATIONCART = "TOGGLE_DONATIONCART";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
